"""empty message

Revision ID: e2d4c8642227
Revises: 
Create Date: 2018-06-29 17:48:53.039128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2d4c8642227'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_object',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('group', sa.String(length=20), server_default='', nullable=False),
    sa.Column('key', sa.String(length=50), server_default='', nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_object')
    # ### end Alembic commands ###
